### ISSUE TITLE
使用电影名称作为存放路径时报错，且电影名称获取错误

### ISSUE THREAD

**Issue by Loryoung** [ylqjgm/AVMeta#7]
**ERROR:**

> SSNI-001.mp4] 刮削失败, 错误原因: open D:\AVMeta/success/#葵/ManyMany.../fanart.jpg: The system cannot find the path specified.

**config.yaml:**

> directory: '#{actor}/{title}'

**Comment by ylqjgm** [comment]
不要使用特殊符号
