### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by wenp5454** [ylqjgm/AVMeta#9]
黑群晖ds3617完美运行，感谢作者贡献，说几个实际使用中的小问题：
1、预编译版没有更新，我先用的预编译版然后报错找不到封面，后来才发现是预编译还在1.0.1，更新为源码版解决。
2、javdb免翻地址已变为javdb8，原来的地址被废弃了
3、封面图和大部分信息都可以获取，但标题几乎没有更改（保留了我群晖里纯番号的命名格式），少部分演出者是可以在cmd下的一些网站上找到的但还是显示未知作者，想问一下脚本是如何选择爬取哪个网站的
祝生活愉快

**Comment by wenp5454** [comment]
尝试更改了scraper中javdb.go里面的代码，将获取标题部分改为了s.root.Find('h2').Text()，现在能正常获取标题了，但出现了之前能获取封面的视频无法更新信息的问题，然后查了一下这个影片在dmm中没有找到但在javdb中能找到，查看docker内v2ray的日志发现只访问了dmm，但其它正常抓取的视频看tag明显是从javdb抓的，不知道是什么问题，希望作者大佬解惑一下

**Comment by LemonDrug** [comment]
您好，我重新编译了，但是没有办法获取，报错404 Not Found 麻烦大佬帮我看一下是不是我的配置信息有问题，谢谢啦。
如果您方便的话，麻烦您将打包好的发我一下15868633@qq.com
`base:
  proxy: "http://127.0.0.1:1080"
media:
  library: vsmeta
  url: ""
  api: ""
  secretid: ""
  secretkey: ""
path:
  success: success
  fail: fail
  directory: '{number}'
  filter: -hd||hd-||_hd||hd_||[||]||【||】||asfur||~||-full||_full||3xplanet||monv||云中飘荡||@||tyhg999.com||xxxxxxxx||-fhd||_fhd||thz.la
site:
  javbus: https://www.javbus.com/
  javdb: https://javdb8.com/`

**Comment by ylqjgm** [comment]
> 黑群晖ds3617完美运行，感谢作者贡献，说几个实际使用中的小问题：
> 1、预编译版没有更新，我先用的预编译版然后报错找不到封面，后来才发现是预编译还在1.0.1，更新为源码版解决。
> 2、javdb免翻地址已变为javdb8，原来的地址被废弃了
> 3、封面图和大部分信息都可以获取，但标题几乎没有更改（保留了我群晖里纯番号的命名格式），少部分演出者是可以在cmd下的一些网站上找到的但还是显示未知作者，想问一下脚本是如何选择爬取哪个网站的
> 祝生活愉快

1. 预编译是自动更新的，只要有新版本就会自动编译
2. javdb这个地址无所谓，在配置里可以自己设置
3. 已经为javdb重新更新了下规则

**Comment by ylqjgm** [comment]
> 您好，我重新编译了，但是没有办法获取，报错404 Not Found 麻烦大佬帮我看一下是不是我的配置信息有问题，谢谢啦。
> 如果您方便的话，麻烦您将打包好的发我一下[15868633@qq.com](mailto:15868633@qq.com)
> `base: proxy: "http://127.0.0.1:1080" media: library: vsmeta url: "" api: "" secretid: "" secretkey: "" path: success: success fail: fail directory: '{number}' filter: -hd||hd-||_hd||hd_||[||]||【||】||asfur||~||-full||_full||3xplanet||monv||云中飘荡||@||tyhg999.com||xxxxxxxx||-fhd||_fhd||thz.la site: javbus: https://www.javbus.com/ javdb: https://javdb8.com/`

你使用代理了么？没使用就去掉代理配置
